# Generated by Django 3.1.2 on 2020-12-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lumber', models.IntegerField(default=0)),
                ('brick', models.IntegerField(default=0)),
                ('wool', models.IntegerField(default=0)),
                ('grain', models.IntegerField(default=0)),
                ('ore', models.IntegerField(default=0)),
                ('dev_knight', models.IntegerField(default=0)),
                ('dev_one_victory_point', models.IntegerField(default=0)),
                ('dev_road_building', models.IntegerField(default=0)),
                ('dev_monopoly', models.IntegerField(default=0)),
                ('dev_year_of_plenty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('turn_id', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ST', 'Settle'), ('MA', 'Main'), ('ED', 'End')], default='ST', max_length=2)),
                ('number_of_player', models.PositiveIntegerField(default=2)),
                ('current_player', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('card_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catan.cardset')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LUMBER', 'Lumber'), ('BRICK', 'Brick'), ('W00L', 'Wool'), ('GRAIN', 'Grain'), ('ORE', 'Ore'), ('DESERT', 'Desert'), ('SEA', 'Sea')], default='LUMBER', max_length=10)),
                ('number', models.PositiveIntegerField(default=2, null=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
            ],
        ),
        migrations.CreateModel(
            name='RobberHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('is_knight', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=False)),
                ('turn_id', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_robber', to='catan.player')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.player')),
            ],
        ),
        migrations.CreateModel(
            name='HarborSea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LR', 'Lumber'), ('BK', 'Brick'), ('WL', 'Wool'), ('GN', 'Grain'), ('OE', 'Ore'), ('AY', 'Any3')], default='AY', max_length=10)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
            ],
        ),
        migrations.CreateModel(
            name='HarborLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.harborsea')),
            ],
        ),
        migrations.CreateModel(
            name='DiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice1', models.PositiveIntegerField(default=1)),
                ('dice2', models.PositiveIntegerField(default=1)),
                ('turn_id', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.player')),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HS', 'House'), ('TN', 'Town'), ('RD', 'Road')], default='RD', max_length=10)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.player')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catan.cardset')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catan.game')),
            ],
        ),
    ]
